Added RetroReaderTestGenerator to do common setup for tests.  Also added RetroReaderCorrelationTest but for some reasons the query doesn't work due to following:
org.springframework.dao.InvalidDataAccessResourceUsageException: could not execute query; SQL [SELECT C.TIME AS TIME_C, C.ID1 AS ID1_C, C.ID2 AS ID2_C, P.TIME AS TIME_P, P.ID AS ID_P FROM CORRELATION C LEFT JOIN POINT P ON C.ID2 = P.ID AND (C.ID2 <> '' AND C.ID2 IS NOT NULL) AND C.POINT = 'POINT25' AND P.POINT = 'POINT5WA']; nested exception is org.hibernate.exception.SQLGrammarException: could not execute query

Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "id1_0_0_" not found [42122-199]